### ISSUE TITLE
Why do I recieve an error such "No module named 'diaphora_heuristics'"

### ISSUE THREAD

**Issue by elvin365** [Sentinel-One/brick#9]
I'm trying to check if my uefi image has vulns. But I get an error:
![image](https://user-images.githubusercontent.com/55601311/147675570-ccf146c9-4fd1-4630-9195-83183e290c06.png)

Why do I get this red error? I've checked if this module is imported in the source code. And obviously it's imported in diaphora.py:

### from diaphora_heuristics import *

How to fix this probem?
P.S. I have not done an optional rizzo signature and added it to 'brick/modules/buffer_outside_smm/sig' , because I still get this error

**Comment by assafcarlsbad** [comment]
Hi,
Sorry for the lack of responsiveness of my side.
I don't know what exactly causes this `import` statement to fail, but I'm afraid the whole attempt to use `Diaphora` in order to identify library functions in UEFI binaries is basically a failed experiment. In the upcoming release of brick I intend to get rid of all that code and stick to plain & simple heuristics in order to identify library functions of interest. Until then, I suggest you comment out all the brick code that uses Diaphora for such purposes and then re-run the tool again.
Hope that helps 🙏 

(I'm closing the issue for now, feel free to re-open if you have further questions)
